# Inserts a blank line between shell prompts
add_newline = true

[[battery.display]]
threshold = 20
style = "bold red"

[cmd_duration]
min_time = 250
show_milliseconds = true

[git_status]
conflicted = "🏳"
# up_to_date = "✓"
untracked = "🤔"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "🏷️"
deleted = "🗑"

[memory_usage]
disabled = false
threshold = 80
symbol = "🐏 "
format = "via $symbol [${ram_pct} RAM]($style) "
style = "bold dimmed red"
